<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('produk')->truncate();
        DB::table('produk_mart')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $products = [
            // --- KATEGORI 1: MAKANAN ---
            ['cat' => 1, 'name' => 'Indomie Goreng Spesial isi 5', 'desc' => 'Paket hemat Indomie Goreng Spesial isi 5 bungkus. Dibuat dari tepung terigu berkualitas dengan perpaduan rempah-rempah pilihan terbaik, dilengkapi dengan bawang goreng renyah dan saus cabai mantap. Sangat cocok sebagai stok makanan praktis di kamar asrama saat lembur tugas.', 'price' => 15500, 'stok' => 50, 'img' => 'produk/makanan_indomie.jpg'],
            ['cat' => 1, 'name' => 'Beras Setra Ramos Super 5kg', 'desc' => 'Beras putih kualitas premium jenis Setra Ramos. Memiliki karakteristik butiran panjang, bersih dari gabah, dan menghasilkan nasi yang pulen serta beraroma wangi alami tanpa pemutih atau pengawet. Pilihan sehat untuk kebutuhan konsumsi harian mahasiswa.', 'price' => 78000, 'stok' => 20, 'img' => 'produk/makanan_beras.jpg'],
            ['cat' => 1, 'name' => 'Sarden ABC Tomat 155g', 'desc' => 'Ikan sarden segar pilihan dalam saus tomat yang kaya rasa. Mengandung Omega 3 dan 6 yang baik untuk kesehatan otak. Dikemas dalam kaleng praktis yang mudah dibuka (easy open), ideal untuk menu makan cepat saji yang bergizi tinggi.', 'price' => 10500, 'stok' => 30, 'img' => 'produk/makanan_sarden.jpg'],
            ['cat' => 1, 'name' => 'Telur Ayam Negeri 10 butir', 'desc' => 'Telur ayam negeri segar pilihan, kaya akan protein hewani untuk menjaga stamina tubuh. Kami pastikan telur dalam kondisi bersih dan tidak retak. Sumber nutrisi esensial yang sangat mudah diolah menjadi berbagai menu sarapan sehat.', 'price' => 28000, 'stok' => 15, 'img' => 'produk/makanan_telur.jpg'],
            ['cat' => 1, 'name' => 'Kecap Manis Bango 520ml', 'desc' => 'Kecap manis legendaris yang terbuat dari 4 bahan alami pilihan: kedelai hitam Malika berkualitas, air, gula, dan garam. Memberikan rasa manis gurih yang meresap sempurna ke dalam masakan, menjadikan setiap hidangan asrama terasa seperti masakan rumah.', 'price' => 22000, 'stok' => 25, 'img' => 'produk/makanan_kecap.jpg'],
            ['cat' => 1, 'name' => 'Kornet Sapi Pronas 198g', 'desc' => 'Daging sapi olahan berkualitas dalam kaleng. Tekstur daging yang lembut dengan bumbu yang meresap, sangat lezat dicampurkan ke dalam mie instan, nasi goreng, atau dibuat perkedel kornet sebagai teman makan nasi hangat.', 'price' => 24500, 'stok' => 18, 'img' => 'produk/makanan_kornet.jpg'],
            ['cat' => 1, 'name' => 'Nugget Ayam Fiesta 500g', 'desc' => 'Nugget ayam premium dengan kandungan daging ayam yang tinggi dan bumbu rahasia Fiesta. Tekstur luar yang renyah setelah digoreng namun sangat lembut di dalam. Pilihan lauk praktis bagi mahasiswa yang memiliki jadwal kuliah padat.', 'price' => 45000, 'stok' => 12, 'img' => 'produk/makanan_nugget.jpg'],

            // --- KATEGORI 2: MINUMAN ---
            ['cat' => 2, 'name' => 'Pocari Sweat Isotonik 500ml', 'desc' => 'Minuman isotonik pengganti ion tubuh yang hilang melalui keringat. Memiliki komposisi yang mirip dengan cairan tubuh sehingga lebih cepat diserap. Sangat direkomendasikan dikonsumsi setelah berolahraga atau saat kondisi tubuh kurang fit agar tetap terhidrasi.', 'price' => 7500, 'stok' => 60, 'img' => 'produk/minuman_pocari.jpg'],
            ['cat' => 2, 'name' => 'Teh Botol Sosro Original 450ml', 'desc' => 'Teh siap minum yang diseduh dari daun teh asli pilihan melalui proses ekstraksi alami. Rasa teh melati yang khas dan otentik, memberikan kesegaran maksimal saat dikonsumsi dingin. Tanpa pemanis buatan dan bahan pengawet.', 'price' => 6000, 'stok' => 80, 'img' => 'produk/minuman_tehbotol.jpg'],
            ['cat' => 2, 'name' => 'Ultra Milk Full Cream 1000ml', 'desc' => 'Susu cair UHT kualitas premium yang berasal dari susu sapi segar alami. Mengandung kalsium, fosfor, dan vitamin yang dibutuhkan untuk pertumbuhan tulang dan energi harian. Rasa gurih alami tanpa tambahan gula, nutrisi harian terbaik untuk mahasiswa.', 'price' => 19500, 'stok' => 24, 'img' => 'produk/minuman_susu.jpg'],
            ['cat' => 2, 'name' => 'Kopi Kapal Api Mantap 165g', 'desc' => 'Perpaduan biji kopi pilihan dari berbagai daerah di Indonesia yang diproses secara modern untuk menghasilkan kopi hitam dengan aroma yang sangat harum dan rasa yang mantap. Teman setia saat mengerjakan tugas kuliah hingga larut malam.', 'price' => 14500, 'stok' => 45, 'img' => 'produk/minuman_kopi.jpg'],
            ['cat' => 2, 'name' => 'Yakult Minuman Probiotik', 'desc' => 'Minuman susu fermentasi yang mengandung bakteri baik L. casei Shirota strain. Membantu menjaga kesehatan pencernaan dan menekan pertumbuhan bakteri merugikan di dalam usus. Cintai ususmu dengan mengonsumsi Yakult setiap hari.', 'price' => 10500, 'stok' => 20, 'img' => 'produk/minuman_yakult.jpg'],
            ['cat' => 2, 'name' => 'Coca-Cola Zero Sugar 330ml', 'desc' => 'Minuman berkarbonasi legendaris dengan sensasi kesegaran Coca-Cola yang otentik namun tanpa kandungan gula sama sekali. Pilihan tepat bagi Anda yang ingin menikmati minuman segar bersoda tanpa khawatir asupan kalori berlebih.', 'price' => 7000, 'stok' => 36, 'img' => 'produk/minuman_coke.jpg'],
            ['cat' => 2, 'name' => 'Buavita Orange Juice 250ml', 'desc' => 'Minuman sari buah jeruk murni yang diperkaya dengan vitamin A, C, dan E. Diproses dengan teknologi tinggi untuk menjaga nutrisi dan rasa segar buah jeruk asli. Membantu meningkatkan daya tahan tubuh agar tetap semangat menjalani rutinitas kampus.', 'price' => 8500, 'stok' => 30, 'img' => 'produk/minuman_buavita.jpg'],
            ['cat' => 2, 'name' => 'Milo Activ-Go Cokelat 22g x 11', 'desc' => 'Minuman cokelat berenergi yang mengandung Protomalt, vitamin, dan mineral. Memberikan energi ekstra untuk aktivitas fisik dan konsentrasi belajar. Format sachet praktis yang mudah dibawa dan diseduh kapan saja di pantry asrama.', 'price' => 32000, 'stok' => 15, 'img' => 'produk/minuman_milo.jpg'],
            ['cat' => 2, 'name' => 'Bear Brand Susu Steril 189ml', 'desc' => 'Susu sapi murni yang telah melalui proses sterilisasi tanpa tambahan bahan pengawet. Membantu menjaga kondisi tubuh tetap fit dan memulihkan stamina saat kelelahan. Tekstur susu yang ringan dan menyegarkan saat dikonsumsi.', 'price' => 10500, 'stok' => 40, 'img' => 'produk/minuman_bearbrand.jpg'],
            ['cat' => 2, 'name' => 'Aqua Air Mineral 1500ml', 'desc' => 'Air mineral yang berasal dari sumber mata air pegunungan yang terlindungi. Melalui proses penyaringan alami yang ketat untuk menjamin kemurnian dan kesegaran air. Kemasan besar 1.5L ideal sebagai stok air minum harian di meja belajar Anda.', 'price' => 6500, 'stok' => 100, 'img' => 'produk/minuman_aqua.jpg'],

            // --- KATEGORI 3: ALAT TULIS ---
            ['cat' => 3, 'name' => 'Sinar Dunia Paper A4 80gr', 'desc' => 'Kertas fotokopi premium dengan tingkat keputihan maksimal dan permukaan halus. Ketebalan 80gr sangat ideal untuk mencetak dokumen penting, laporan tugas akhir, atau skripsi tanpa risiko paper jam pada printer. Isi 500 lembar per rim.', 'price' => 56000, 'stok' => 20, 'img' => 'produk/atk_kertas.jpg'],
            ['cat' => 3, 'name' => 'Pulpen Joyko Gel 0.5mm Hitam', 'desc' => 'Pulpen tinta gel kualitas tinggi dengan ukuran mata pena 0.5mm. Menghasilkan tulisan yang tajam, hitam pekat, dan tinta sangat cepat kering (anti-smudge). Desain ergonomis yang nyaman digunakan untuk mencatat materi kuliah dalam durasi lama.', 'price' => 5000, 'stok' => 150, 'img' => 'produk/atk_pulpen.jpg'],
            ['cat' => 3, 'name' => 'Binder Note B5 26 Ring', 'desc' => 'Buku catatan sistem binder ukuran B5 dengan 26 ring besi yang kuat. Sampul terbuat dari bahan plastik tebal transparan yang elegan. Memudahkan Anda mengorganisir catatan perkuliahan per semester dengan rapi. Bonus kertas loose leaf di dalamnya.', 'price' => 25000, 'stok' => 12, 'img' => 'produk/atk_binder.jpg'],
            ['cat' => 3, 'name' => 'Stabilo Boss Original Pastel', 'desc' => 'Highlighter premium dengan teknologi anti-dry-out (tidak kering meski tutup dibuka hingga 4 jam). Warna pastel yang lembut di mata namun tetap efektif untuk menandai poin-poin penting pada buku teks atau catatan kuliah.', 'price' => 15000, 'stok' => 40, 'img' => 'produk/atk_stabilo.jpg'],
            ['cat' => 3, 'name' => 'Pensil Mekanik Pilot 0.5mm', 'desc' => 'Pensil mekanik dengan body transparan yang stylish dan fitur retractable tip untuk melindungi ujung pensil agar tidak patah. Mekanisme lead advance yang halus dan handal. Sangat cocok untuk pengerjaan soal hitungan atau sketsa diagram.', 'price' => 18500, 'stok' => 30, 'img' => 'produk/atk_pensil.jpg'],
            ['cat' => 3, 'name' => 'Penghapus Boxy Hitam Kecil', 'desc' => 'Penghapus legendaris dari Jepang yang sangat efektif menghapus goresan pensil tanpa meninggalkan bekas noda hitam atau merusak permukaan kertas. Hasil hapusan bersih dan kotoran sisa penghapus menggumpal sehingga mudah dibersihkan.', 'price' => 7000, 'stok' => 50, 'img' => 'produk/atk_penghapus.jpg'],
            ['cat' => 3, 'name' => 'Penggaris Besi 30cm Kenko', 'desc' => 'Penggaris yang terbuat dari bahan stainless steel anti karat berkualitas tinggi. Angka pengukuran yang digrafir secara permanen sehingga tidak akan luntur atau hilang. Sangat presisi dan tahan banting untuk penggunaan jangka panjang di kampus.', 'price' => 8000, 'stok' => 25, 'img' => 'produk/atk_penggaris.jpg'],
            ['cat' => 3, 'name' => 'Map Folder L-Shape Transparan', 'desc' => 'Folder penyimpanan dokumen berbentuk L ukuran A4. Terbuat dari bahan plastik fleksibel bening untuk memudahkan identifikasi isi dokumen di dalamnya. Melindungi tugas atau formulir penting Anda agar tidak tertekuk atau basah.', 'price' => 2500, 'stok' => 100, 'img' => 'produk/atk_map.jpg'],
            ['cat' => 3, 'name' => 'Cairan Koreksi Joyko 12ml', 'desc' => 'Tip-ex kertas berbentuk cair dengan aplikator metal point yang presisi. Menutup tulisan yang salah secara merata, cepat kering, dan tidak menggumpal saat ditulis ulang di atasnya.', 'price' => 4500, 'stok' => 60, 'img' => 'produk/atk_tipex.jpg'],
            ['cat' => 3, 'name' => 'Post-it Note 3x3 Kuning', 'desc' => 'Kertas catatan tempel original dengan daya rekat yang kuat namun tidak meninggalkan sisa lem saat dicabut. Sangat efektif digunakan sebagai pengingat (reminder) tugas di monitor laptop atau menandai halaman penting.', 'price' => 12000, 'stok' => 35, 'img' => 'produk/atk_postit.jpg'],

            // --- KATEGORI 4: SNACK ---
            ['cat' => 4, 'name' => 'Potabee Seaweed 68g', 'desc' => 'Keripik kentang renyah dengan potongan V-cut unik yang memberikan sensasi "kriuk" maksimal. Dibumbui dengan serpihan rumput laut asli yang gurih dan melimpah. Camilan lezat yang sulit dihentikan setelah gigitan pertama saat santai di asrama.', 'price' => 10500, 'stok' => 40, 'img' => 'produk/snack_potabee.jpg'],
            ['cat' => 4, 'name' => 'Chitato Sapi Panggang 68g', 'desc' => 'Kripik kentang bergelombang yang terbuat dari kentang asli pilihan. Rasa sapi panggang yang kuat dan bumbu yang meresap sempurna hingga ke dalam serat kentang. Snack ikonik Indonesia yang selalu pas menemani waktu kumpul bersama teman.', 'price' => 11000, 'stok' => 40, 'img' => 'produk/snack_chitato.jpg'],
            ['cat' => 4, 'name' => 'Pringles Original 107g', 'desc' => 'Keripik kentang berbentuk parabola yang ikonik dengan tekstur yang sangat halus dan renyah. Dikemas dalam kaleng tabung praktis yang menjaga keripik tetap utuh dan tidak hancur. Rasa original yang gurih klasik, cocok dinikmati kapan saja.', 'price' => 18500, 'stok' => 20, 'img' => 'produk/snack_pringles.jpg'],
            ['cat' => 4, 'name' => 'Oreo Sandwich Cokelat 119g', 'desc' => 'Biskuit cokelat renyah dengan krim rasa vanilla yang manis di tengahnya. Nikmati dengan cara "Diputar, Dijilat, Dicelupin" ke dalam segelas susu hangat untuk sensasi rasa yang lebih nikmat.', 'price' => 9500, 'stok' => 35, 'img' => 'produk/snack_oreo.jpg'],
            ['cat' => 4, 'name' => 'SilverQueen Cashew 58g', 'desc' => 'Cokelat susu premium dengan taburan kacang mede renyah di setiap gigitannya. Perpaduan sempurna antara kelembutan cokelat asli dan gurihnya kacang mede berkualitas. Peningkat mood (booster) terbaik saat stres menghadapi ujian perkuliahan.', 'price' => 15500, 'stok' => 25, 'img' => 'produk/snack_chocolate.jpg'],
            ['cat' => 4, 'name' => 'Beng-Beng Share It 10x9.5g', 'desc' => 'Wafer lapis cokelat dengan sereal renyah, karamel manis, dan cokelat susu yang melimpah. Hadir dalam kemasan pouch berisi 10 keping ukuran kecil (bite size), memudahkan Anda berbagi keceriaan bersama teman sejawat di asrama.', 'price' => 12500, 'stok' => 30, 'img' => 'produk/snack_bengbeng.jpg'],
            ['cat' => 4, 'name' => 'Qtela Singkong Balado 60g', 'desc' => 'Keripik singkong tradisional Indonesia dengan cita rasa modern. Terbuat dari singkong asli yang diiris tipis dan digoreng hingga renyah, dibalut bumbu balado pedas manis yang menggoda selera.', 'price' => 6000, 'stok' => 50, 'img' => 'produk/snack_qtela.jpg'],
            ['cat' => 4, 'name' => 'Garuda Kacang Atom 130g', 'desc' => 'Kacang tanah pilihan yang dibalut tepung terigu renyah berwarna putih bersih. Tekstur yang sangat garing dengan rasa gurih yang khas. Camilan yang sangat seru dikonsumsi saat menonton film atau berdiskusi kelompok di area belajar.', 'price' => 9000, 'stok' => 40, 'img' => 'produk/snack_kacang.jpg'],
            ['cat' => 4, 'name' => 'Roma Kelapa Biskuit 300g', 'desc' => 'Biskuit yang terbuat dari kelapa asli pilihan dan diperkaya dengan Vitamin B1, B2, B6, B12, dan E. Aroma kelapa yang wangi dan rasa manis yang pas, sangat nikmat dicelupkan ke dalam kopi atau teh hangat.', 'price' => 10500, 'stok' => 25, 'img' => 'produk/snack_roma.jpg'],
            ['cat' => 4, 'name' => 'Pop Mie Rasa Ayam 75g', 'desc' => 'Mie instan dalam kemasan cup praktis dengan rasa kaldu ayam yang gurih. Cukup seduh dengan air panas selama 3 menit, Anda sudah bisa menikmati hidangan hangat yang lezat lengkap dengan sayuran kering di dalamnya. Penolong lapar di tengah malam.', 'price' => 5500, 'stok' => 100, 'img' => 'produk/snack_popmie.jpg'],

            // --- KATEGORI 5: PERLENGKAPAN KEBERSIHAN ---
            ['cat' => 5, 'name' => 'Lifebuoy Sabun Cair 450ml', 'desc' => 'Sabun mandi cair dengan perlindungan total 10 melawan kuman. Formula mutakhirnya dapat membersihkan kulit secara mendalam hingga ke pori-pori dan menghilangkan bau badan. Memberikan kesegaran tahan lama setelah mandi seharian di kampus.', 'price' => 24000, 'stok' => 20, 'img' => 'produk/clean_soap.jpg'],
            ['cat' => 5, 'name' => 'Pepsodent Pasta Gigi 190g', 'desc' => 'Pasta gigi dengan formula mikro kalsium aktif dan pro-fluoride kompleks yang bekerja siang dan malam untuk menutup lubang kecil tak kasat mata pada gigi. Memberikan perlindungan maksimal dari gigi berlubang dan nafas segar sepanjang hari.', 'price' => 13500, 'stok' => 30, 'img' => 'produk/clean_odol.jpg'],
            ['cat' => 5, 'name' => 'Clear Shampoo Anti Ketombe 160ml', 'desc' => 'Sampo anti ketombe nomor 1 di Indonesia dengan teknologi Triple Anti-Dandruff. Menghilangkan ketombe, menutrisi kulit kepala, dan memberikan sensasi dingin maksimal (menthol blast) yang menyegarkan rambut dari polusi dan keringat.', 'price' => 26000, 'stok' => 25, 'img' => 'produk/clean_shampoo.jpg'],
            ['cat' => 5, 'name' => 'Mama Lemon Jeruk Nipis 780ml', 'desc' => 'Cairan pencuci piring ekstrak jeruk nipis asli yang memiliki daya cuci 3x lebih cepat dalam melarutkan lemak membandel. Menghilangkan bau amis pada wadah plastik atau peralatan makan dengan sekali bilas.', 'price' => 14000, 'stok' => 35, 'img' => 'produk/clean_mamalemon.jpg'],
            ['cat' => 5, 'name' => 'So Klin Liquid Deterjen 750ml', 'desc' => 'Deterjen cair konsentrat dengan formula Power Clean Action yang mampu mengangkat noda membandel hingga ke serat kain terdalam tanpa merusak warna baju. Wangi parfum mewah yang tahan lama meski dijemur di dalam asrama tanpa sinar matahari langsung.', 'price' => 18500, 'stok' => 30, 'img' => 'produk/clean_detergen.jpg'],
            ['cat' => 5, 'name' => 'Molto Softener Blue 800ml', 'desc' => 'Pelembut dan pewangi pakaian konsentrat dengan teknologi enkapsulasi parfum yang memberikan keharuman tahan lama hingga 14 hari. Membuat serat kain menjadi sangat lembut, mudah disetrika, dan tidak menyebabkan iritasi pada kulit.', 'price' => 22000, 'stok' => 20, 'img' => 'produk/clean_molto.jpg'],
            ['cat' => 5, 'name' => 'Wipol Karbol Wangi 750ml', 'desc' => 'Cairan pembersih lantai dengan aroma cemara khas yang efektif membunuh 99% kuman dan bakteri. Menghilangkan bau tidak sedap pada lantai kamar mandi atau area komunal asrama, serta memberikan sensasi kesegaran alami yang menenangkan.', 'price' => 16000, 'stok' => 15, 'img' => 'produk/clean_wipol.jpg'],
            ['cat' => 5, 'name' => 'Stella Matic Refill 225ml', 'desc' => 'Isi ulang pengharum ruangan otomatis dengan berbagai pilihan aroma bunga atau buah yang segar. Sangat efektif menghilangkan bau apek dan menyegarkan udara di dalam kamar asrama. Memberikan kenyamanan lebih saat beristirahat atau belajar.', 'price' => 28000, 'stok' => 10, 'img' => 'produk/clean_stella.jpg'],
            ['cat' => 5, 'name' => 'Harpic Penghancur Kerak 450ml', 'desc' => 'Pembersih toilet paling ampuh dengan formula kental yang menempel pada permukaan porselen untuk menghancurkan kerak membandel, noda kuning, serta membunuh kuman. Membuat toilet asrama bersih berkilau dan bebas bau dalam hitungan menit.', 'price' => 19500, 'stok' => 12, 'img' => 'produk/clean_harpic.jpg'],
            ['cat' => 5, 'name' => 'Gillette Blue II Flexi Razor', 'desc' => 'Alat cukur pria dengan dua mata pisau tipis berkualitas tinggi dan kepala yang fleksibel mengikuti lekuk wajah. Dilengkapi dengan strip pelicin (lubrastrip) yang mengandung vitamin E untuk mencegah iritasi kulit saat mencukur. Sangat awet dan higienis.', 'price' => 12000, 'stok' => 40, 'img' => 'produk/clean_gillete.jpg'],

            // --- KATEGORI 6: ELEKTRONIK ---
            ['cat' => 6, 'name' => 'Kabel Data Robot Type-C 1M', 'desc' => 'Kabel data pengisian daya cepat (fast charging) 2.4A dengan material kabel berkualitas yang elastis dan anti-lilit. Bagian ujung konektor dilapisi metal yang kuat sehingga tidak mudah patah. Mendukung sinkronisasi data dengan kecepatan tinggi ke laptop.', 'price' => 25000, 'stok' => 30, 'img' => 'produk/electro_kabel.jpg'],
            ['cat' => 6, 'name' => 'Mouse Wireless Logitech B170', 'desc' => 'Mouse nirkabel handal dengan teknologi optik 1000 DPI yang presisi. Menggunakan koneksi 2.4GHz via USB nano receiver yang stabil hingga jarak 10 meter. Hemat energi, satu baterai AA bisa bertahan hingga 12 bulan penggunaan normal kuliah.', 'price' => 110000, 'stok' => 10, 'img' => 'produk/electro_mouse.jpg'],
            ['cat' => 6, 'name' => 'Earphone Samsung Tuned by AKG', 'desc' => 'Earphone berkualitas tinggi dengan hasil suara yang jernih dan bass yang mendalam (deep bass). Dilengkapi dengan mikrofon untuk keperluan meeting online atau telepon, serta tombol kontrol volume yang intuitif. Kabel kain yang kuat dan anti-kusut.', 'price' => 85000, 'stok' => 15, 'img' => 'produk/electro_earphone.jpg'],
            ['cat' => 6, 'name' => 'Flashdisk Sandisk Cruzer 32GB', 'desc' => 'Media penyimpanan data portabel dengan desain slide-out yang praktis untuk melindungi konektor USB. Kapasitas 32GB yang lega untuk menyimpan ribuan dokumen kuliah, foto, dan video. Kecepatan transfer data yang stabil dan kompatibilitas universal.', 'price' => 68000, 'stok' => 25, 'img' => 'produk/electro_flashdisk.jpg'],
            ['cat' => 6, 'name' => 'Baterai Alkaline AA 2+1 Pack', 'desc' => 'Baterai primer kualitas premium yang mampu memberikan daya hingga 10x lebih lama dibandingkan baterai biasa. Sangat direkomendasikan untuk perangkat elektronik seperti mouse wireless, jam dinding, atau kalkulator yang membutuhkan aliran listrik stabil.', 'price' => 18000, 'stok' => 40, 'img' => 'produk/electro_baterai.jpg'],
            ['cat' => 6, 'name' => 'Terminal Colokan 3 Lubang 3M', 'desc' => 'Kabel perpanjangan (extension) dengan 3 lubang colokan universal yang dilengkapi saklar On/Off mandiri dan lampu indikator. Kabel tebal kualitas SNI sepanjang 3 meter, solusi tepat untuk mengatasi keterbatasan stop kontak di kamar asrama.', 'price' => 48000, 'stok' => 20, 'img' => 'produk/electro_colokan.jpg'],

            // --- KATEGORI 9: LAINNYA ---
            ['cat' => 9, 'name' => 'Tissue Paseo Soft Pack 250 Sheets', 'desc' => 'Tisu wajah 2 ply yang terbuat dari 100% serat alami (Virgin Plantation Pulp). Memiliki tekstur yang sangat lembut dan kuat sehingga tidak mudah hancur saat terkena air. Aman digunakan untuk kulit sensitif dan kebutuhan higienis harian.', 'price' => 12500, 'stok' => 60, 'img' => 'produk/misc_tissue.jpg'],
            ['cat' => 9, 'name' => 'Payung Lipat Anti-UV Hitam', 'desc' => 'Payung lipat praktis dengan lapisan silver/hitam pelindung radiasi matahari (anti-UV). Rangka jari-jari yang fleksibel dan tahan angin (windproof). Ukuran sangat kompak saat dilipat, mudah dimasukkan ke dalam tas kuliah.', 'price' => 48000, 'stok' => 20, 'img' => 'produk/misc_payung.jpg'],
            ['cat' => 9, 'name' => 'Minyak Kayu Putih Cap Lang 60ml', 'desc' => 'Minyak kayu putih murni yang membantu meredakan sakit perut, perut kembung, mual, dan gatal-gatal akibat gigitan serangga. Memberikan rasa hangat yang menenangkan pada tubuh, wajib ada di kotak P3K setiap kamar asrama.', 'price' => 21000, 'stok' => 30, 'img' => 'produk/misc_kayuputih.jpg'],
            ['cat' => 9, 'name' => 'Sandal Jepit Swallow Classic', 'desc' => 'Sandal jepit karet legendaris yang sangat kuat dan nyaman digunakan. Terbuat dari karet alami yang anti selip, sangat cocok untuk digunakan ke kamar mandi atau santai di area sekitar asrama. Pilihan awet dengan harga paling terjangkau.', 'price' => 14000, 'stok' => 50, 'img' => 'produk/misc_sandal.jpg'],
            ['cat' => 9, 'name' => 'Kapas Wajah Selection 75g', 'desc' => 'Kapas kecantikan kualitas premium yang memiliki tekstur halus dan lembut. Tanpa kandungan klorin atau bahan pemutih berbahaya. Sangat efektif untuk membersihkan sisa makeup atau mengaplikasikan toner pada wajah tanpa meninggalkan serat.', 'price' => 9500, 'stok' => 40, 'img' => 'produk/misc_kapas.jpg'],
            ['cat' => 9, 'name' => 'Korek Gas Tokai Original', 'desc' => 'Korek api gas standar internasional dengan mekanisme pemantik yang aman dan tahan lama. Volume gas yang optimal untuk penggunaan dalam jangka waktu lama. Dilengkapi dengan pengatur besar kecilnya api sesuai kebutuhan.', 'price' => 4000, 'stok' => 100, 'img' => 'produk/misc_korek.jpg'],
            ['cat' => 9, 'name' => 'Gunting Joyko Besar SC-848', 'desc' => 'Gunting serbaguna dengan mata pisau dari stainless steel berkualitas tinggi yang sangat tajam dan presisi. Gagang plastik ergonomis yang nyaman digenggam. Memudahkan Anda dalam mengerjakan tugas prakarya atau membuka paket kiriman belanja.', 'price' => 12500, 'stok' => 15, 'img' => 'produk/misc_gunting.jpg'],
            ['cat' => 9, 'name' => 'Plester Luka Hansaplast isi 10', 'desc' => 'Plester pelindung luka yang elastis dan memiliki sirkulasi udara yang baik. Melindungi luka dari kotoran dan bakteri sehingga proses penyembuhan menjadi lebih cepat. Menggunakan bantalan yang tidak lengket pada luka saat dilepas.', 'price' => 6000, 'stok' => 80, 'img' => 'produk/misc_plester.jpg'],
            ['cat' => 9, 'name' => 'Gantungan Baju Hanger isi 10', 'desc' => 'Paket berisi 10 buah gantungan baju yang terbuat dari kawat berlapis plastik warna-warni. Kuat untuk menggantung jaket atau celana jeans yang berat sekalipun. Membantu menjaga pakaian tetap rapi dan tidak kusut di dalam lemari asrama.', 'price' => 18000, 'stok' => 20, 'img' => 'produk/misc_hanger.jpg'],
            ['cat' => 9, 'name' => 'Minyak Goreng Filma 2L', 'desc' => 'Minyak goreng non-kolesterol yang terbuat dari buah sawit pilihan, diproses secara higienis dengan pemurnian terintegrasi. Menghasilkan minyak bening berkualitas yang membuat gorengan lebih renyah dan sehat. Cocok untuk kebutuhan masak bersama teman kamar.', 'price' => 36500, 'stok' => 20, 'img' => 'produk/makanan_minyak.jpg'],
            ['cat' => 9, 'name' => 'Garam Meja Beriodium 250g', 'desc' => 'Garam halus beriodium kualitas ekspor. Membantu mencegah penyakit gondok dan mendukung kecerdasan. Tekstur sangat halus, putih bersih, dan mudah larut, memberikan rasa asin yang pas pada setiap masakan Anda.', 'price' => 3000, 'stok' => 40, 'img' => 'produk/makanan_garam.jpg'],
            ['cat' => 9, 'name' => 'Sajiku Tepung Bumbu 250g', 'desc' => 'Tepung bumbu serbaguna yang terbuat dari perpaduan tepung dan rempah asli pilihan. Tidak perlu tambahan bumbu lain, membuat ayam, tempe, atau tahu goreng menjadi sangat renyah dan gurih dengan aroma yang menggugah selera.', 'price' => 6500, 'stok' => 50, 'img' => 'produk/makanan_tepung.jpg'],
        ];

        foreach ($products as $p) {
            $produkId = DB::table('produk')->insertGetId([
                'kategori_id'         => $p['cat'],
                'nama_produk'         => $p['name'],
                'deskripsi'           => $p['desc'],
                'harga'               => $p['price'],
                'stok'                => $p['stok'],
                'gambar'              => $p['img'],
                'is_active'           => true,
                'status_ketersediaan' => $p['stok'] > 0 ? 'Tersedia' : 'Habis',
                'persentase_diskon'   => 0,
                'created_at'          => now()->subDays(rand(0, 14)),
                'updated_at'          => now(),
            ]);



            // Sambungkan ke 1-3 mart secara acak
            $randomMarts = collect([1, 2, 3])->shuffle()->take(rand(1, 3));
            foreach ($randomMarts as $martId) {
                DB::table('produk_mart')->insert([
                    'produk_id'  => $produkId,
                    'mart_id'    => $martId,
                    'stok_lokal' => $p['stok'],
                    'harga_lokal'=> $p['price'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }

        $this->command->info('✅ ProdukSeeder: ' . count($products) . ' produk berhasil ditambahkan.');
    }
}